// <auto-generated />
using System;
using Coursera_Exercise.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Coursera_Exercise.Migrations
{
    [DbContext(typeof(CourseraExerciseContext))]
    [Migration("20251127071131_Init Models")]
    partial class InitModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Coursera_Exercise.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("Credit")
                        .HasColumnType("smallint");

                    b.Property<int>("Instructor_id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time_created")
                        .HasColumnType("datetime2");

                    b.Property<short>("Total_time")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("Instructor_id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Coursera_Exercise.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("First_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time_created")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("Coursera_Exercise.Models.Student", b =>
                {
                    b.Property<string>("PIN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("First_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time_created")
                        .HasColumnType("datetime2");

                    b.HasKey("PIN");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Coursera_Exercise.Models.StudentCourse", b =>
                {
                    b.Property<string>("Student_pin")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Course_id")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Completion_Date")
                        .HasColumnType("date");

                    b.HasKey("Student_pin", "Course_id");

                    b.HasIndex("Course_id");

                    b.ToTable("StudentsCourse");
                });

            modelBuilder.Entity("Coursera_Exercise.Models.Course", b =>
                {
                    b.HasOne("Coursera_Exercise.Models.Instructor", "_Instructor")
                        .WithMany()
                        .HasForeignKey("Instructor_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_Instructor");
                });

            modelBuilder.Entity("Coursera_Exercise.Models.StudentCourse", b =>
                {
                    b.HasOne("Coursera_Exercise.Models.Course", "_Course")
                        .WithMany()
                        .HasForeignKey("Course_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Coursera_Exercise.Models.Student", "_Student")
                        .WithMany()
                        .HasForeignKey("Student_pin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_Course");

                    b.Navigation("_Student");
                });
#pragma warning restore 612, 618
        }
    }
}
